(TeX-add-style-hook "_region_"
 (lambda ()
    (TeX-run-style-hooks
     "enumerate"
     "soul"
     "graphicx"
     "ntheorem"
     "thmmarks"
     "amsfonts"
     "amssymb"
     "amsmath"
     ""
     "inputenc"
     "utf8"
     "babel"
     "english"
     "geometry"
     "margin=1in"
     "latex2e"
     "memoir11"
     "memoir"
     "oneside"
     "article"
     "a4paper"
     "11pt"
     "extrapackages"
     "theoremsetup"
     "macrosetup")))

